import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import vm from 'node:vm';
import {TYPES,TARGET,DURATION,createGame,canDeliver,advance,pause,resume,place,redraw,deliver,loadPreferences,savePreferences} from '../play/game.mjs';
function put(state,type){state.cards[0]=type;return place(state,0,type,()=>0);}
function full(state){for(const type of TYPES)put(state,type);}
test('Two required blocks allow an 80 point delivery; optional preference changes reward',()=>{
 const basic=createGame('timed',()=>0);put(basic,'hero');assert.equal(canDeliver(basic),false);put(basic,'cta');assert.equal(canDeliver(basic),true);const result=deliver(basic,()=>0);assert.equal(result.points,60);assert.equal(basic.score,80);assert.equal(basic.deliveries,1);assert.ok(TYPES.every(t=>!basic.slots[t]));
 const preferred=createGame('timed',()=>0);put(preferred,'hero');put(preferred,'cta');put(preferred,preferred.brief.preferred);assert.equal(deliver(preferred,()=>0).points,80);
 const other=createGame('timed',()=>0);put(other,'hero');put(other,'cta');put(other,other.brief.preferred==='services'?'work':'services');assert.equal(deliver(other,()=>0).points,70);
});
test('Full website grants the complete bonus and keeps combo into the next site',()=>{const s=createGame('timed',()=>0);full(s);assert.equal(s.score,60);const result=deliver(s,()=>0);assert.equal(result.points,120);assert.equal(result.full,true);assert.equal(s.score,180);assert.equal(s.fullSites,1);assert.equal(s.streak,4);put(s,'hero');assert.equal(s.score,200);assert.equal(s.bestStreak,5);});
test('Wrong placement cannot overwrite a module; penalty is bounded and breaks combo',()=>{const s=createGame();put(s,'hero');put(s,'cta');s.cards[0]='hero';const before={...s.slots};assert.equal(place(s,0,'hero').kind,'wrong');assert.deepEqual(s.slots,before);assert.equal(s.score,15);assert.equal(s.streak,0);for(let i=0;i<10;i++)place(s,0,'work');assert.equal(s.score,0);const snapshot=JSON.stringify(s);assert.equal(place(s,null,'hero').kind,'hint');assert.equal(JSON.stringify(s),snapshot);});
test('Hand always has a legal move while a slot remains; redraw handles repeated RNG values',()=>{
 let seed=41;const rng=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};
 for(const random of [()=>0,()=>.999999,rng]){const s=createGame('timed',random);for(let turn=0;turn<120;turn++){const empty=TYPES.filter(t=>!s.slots[t]);if(!empty.length){deliver(s,random);continue;}const index=s.cards.findIndex(type=>empty.includes(type));assert.ok(index>=0);place(s,index,s.cards[index],random);if(turn%7===0){redraw(s,random);if(TYPES.some(t=>!s.slots[t]))assert.ok(s.cards.some(t=>!s.slots[t]));}}}
});
test('Opening hand has three distinct choices; refill stays distinct and favors unfinished slots',()=>{let seed=3;const rng=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646;};for(let round=0;round<80;round++){const s=createGame('timed',rng);assert.equal(new Set(s.cards).size,3);assert.ok(s.cards.includes('hero')||s.cards.includes('cta'));for(let step=0;step<4;step++){const index=s.cards.findIndex(t=>!s.slots[t]);assert.ok(index>=0);place(s,index,s.cards[index],rng);assert.equal(new Set(s.cards).size,3);const remaining=TYPES.filter(t=>!s.slots[t]);for(const type of remaining)assert.ok(s.cards.includes(type),'Unfinished choice was unnecessarily hidden');}redraw(s,rng);assert.equal(new Set(s.cards).size,3);}});
test('Exactly 75 active seconds ends once; paused/background gap does not consume time',()=>{const s=createGame();advance(s,1000);pause(s);const snapshot=JSON.stringify(s);advance(s,100000);assert.equal(JSON.stringify(s),snapshot);assert.equal(place(s,0,'hero').kind,'ignored');assert.equal(deliver(s).kind,'ignored');resume(s);assert.equal(advance(s,74000),true);assert.equal(s.remainingMs,0);assert.equal(s.status,'ended');const ended=JSON.stringify(s);advance(s,4000);redraw(s);deliver(s);put(s,'hero');assert.equal(s.status,'ended');assert.equal(s.score,JSON.parse(ended).score);assert.equal(advance(s,1),false);});
test('Practice ignores the clock and ends on the sixth valid delivery, never the fifth',()=>{const s=createGame('practice');advance(s,10*DURATION);assert.equal(s.remainingMs,DURATION);for(let i=0;i<6;i++){assert.equal(s.status,'playing');put(s,'hero');put(s,'cta');deliver(s);}assert.equal(s.status,'ended');assert.equal(s.deliveries,6);assert.equal(s.score,580);assert.ok(s.score<TARGET);});
test('A complete practice game can win; new game resets every round and timer field',()=>{const s=createGame('practice');for(let i=0;i<6;i++){full(s);deliver(s);}assert.ok(s.score>=TARGET);assert.equal(s.fullSites,6);const retry=createGame('practice');assert.equal(retry.score,0);assert.equal(retry.deliveries,0);assert.equal(retry.streak,0);assert.equal(retry.remainingMs,DURATION);assert.equal(retry.status,'playing');});
test('Bad elapsed values cannot add time or corrupt the clock',()=>{const s=createGame();advance(s,-100);advance(s,NaN);advance(s,Infinity);assert.equal(s.remainingMs,DURATION);advance(s,75_001);assert.equal(s.remainingMs,0);});
test('Storage blocked, corrupt or wrong-version data never blocks play',()=>{const fallback={sound:false,best:{timed:0,practice:0}};assert.deepEqual(loadPreferences(null),fallback);assert.deepEqual(loadPreferences({getItem(){throw Error('blocked');}}),fallback);assert.deepEqual(loadPreferences({getItem:()=>'{oops'}),fallback);assert.deepEqual(loadPreferences({getItem:()=>JSON.stringify({version:2,sound:true,best:{timed:999}})}),fallback);assert.equal(savePreferences({setItem(){throw Error('full');}},fallback),false);assert.equal(savePreferences(null,fallback),false);const s=createGame('practice');full(s);assert.equal(deliver(s).kind,'delivered');});
test('Best scores are validated and kept separate by mode; initial sound is muted',()=>{const stored={version:1,sound:true,best:{timed:420,practice:900}};let value=JSON.stringify(stored);const memory={getItem:()=>value,setItem:(key,next)=>{assert.equal(key,'heycheng-play-v1');value=next;}};const prefs=loadPreferences(memory);assert.deepEqual(prefs, {sound:true,best:{timed:420,practice:900}});assert.equal(savePreferences(memory,prefs),true);assert.deepEqual(JSON.parse(value),stored);assert.deepEqual(loadPreferences({getItem:()=>JSON.stringify({version:1,sound:'true',best:{timed:-1,practice:'900'}})}),{sound:false,best:{timed:0,practice:0}});});
const sw=await readFile(new URL('../play/sw.js',import.meta.url),'utf8');
function worker(){const handlers={},cached=[],deleted=[],network=[];const cache={addAll:async requests=>cached.push(...requests.map(r=>r.url)),match:async()=>({fromCache:true}),put:async()=>{}};const self={location:{origin:'https://example.test'},addEventListener:(name,fn)=>handlers[name]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{}}};class LocalRequest extends Request{constructor(url,options){super(new URL(url,self.location.origin),options);}}vm.runInNewContext(sw,{self,URL,Request:LocalRequest,caches:{open:async()=>cache,keys:async()=>['unrelated-root-cache','heycheng-play-old'],delete:async name=>deleted.push(name)},fetch:async request=>{network.push(request.url);return {ok:true,type:'basic',clone(){return this;}};}});return {handlers,cached,deleted,network};}
test('Offline install caches only the six public /play assets; activation leaves all other caches intact',async()=>{const w=worker();let pending;w.handlers.install({waitUntil:p=>pending=p});await pending;assert.equal(w.cached.length,6);assert.ok(w.cached.every(url=>new URL(url).pathname.startsWith('/play/')));assert.ok(!w.cached.some(url=>/portal|supabase/.test(url)));w.handlers.activate({waitUntil:p=>pending=p});await pending;assert.deepEqual(w.deleted,['heycheng-play-old']);});
test('Service worker does not intercept root, portal, Auth, APIs, arbitrary play paths, query URLs or non-GET',()=>{const w=worker();for(const [url,method] of [['https://example.test/','GET'],['https://example.test/portal/','GET'],['https://example.test/auth/v1/callback','GET'],['https://project.supabase.co/storage/v1/object','GET'],['https://example.test/play/unknown','GET'],['https://example.test/play/?token=anything','GET'],['https://example.test/play/app.mjs','POST']]){let intercepted=false;w.handlers.fetch({request:new Request(url,{method}),respondWith(){intercepted=true;}});assert.equal(intercepted,false,url);}});
test('Exact offline game route is served from its own cache',async()=>{const w=worker();let pending;w.handlers.fetch({request:new Request('https://example.test/play/'),respondWith:p=>pending=p});assert.deepEqual(await pending,{fromCache:true});assert.equal(w.network.length,0);});
